path:
  data: ../../data/audio_data
  base: ../../resources/audio_emotion/
  features: features/
  normalizer: feature_normalizers/
  normalized: feature_normalized/
  feature_selection: feature_selection/
  models: acoustic_models/

features:
  sr: 22050.0
  win_length_seconds: 0.020
  hop_length_seconds: 0.010

  mfcc:
    window: hamming_asymmetric  # [hann_asymmetric, hamming_asymmetric]
    n_mfcc: 14                  # Number of MFCC coefficients
    n_mels: 40                  # Number of MEL bands used
    n_fft: 1024                 # FFT length
    fmin: 0                     # Minimum frequency when constructing MEL bands
    fmax: 8000                 # Maximum frequency when constructing MEL band
    htk: false                  # Switch for HTK-styled MEL-frequency equation
